# permissions for end users to edit ppws.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ppw-editor-role
rules:
- apiGroups:
  - apps.ppw.example.com
  resources:
  - ppws
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.ppw.example.com
  resources:
  - ppws/status
  verbs:
  - get
