apiVersion: apps.ppw.example.com/v1alpha0
kind: Ppw
metadata:
  name: ppw-sample
spec:
  server:
    size: 2
    image: docker.pkg.github.com/safronovd/python-pravega-writer/ppw-server:latest
    imagePullSecret: github-pkg
