name: Build

on:
  workflow_dispatch:
  push:
    branches: [dev]
  
jobs:
  build:
    name: Building operator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@dev
        
      - name: Set up Go 
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ^1.14
          
      - name: Building app
        run: |
          echo $GOBIN
          echo $GOPATH
          
