name: Build

on:
  workflow_dispatch:
  push:
    branches: [dev]
  
jobs:
  build:
    name: Building operator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        
      - name: Set up Go 
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ^1.15
          
      - name: Building app
        run: |
          go env
          make generate
          make manifests
          make install
          
