name: CI on Dev Workflow

on:
  push:
    branches: [dev]

env:
  IMG: ppw-operator
  GOBIN: /bin
  
jobs:
  build:
    name: Setup enviroment
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        
      - name: Set up Go 
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ^1.15
      
      - name: Set up gcc
        run: sudo apt install build-essential

      - name: Set env vars
        run: |
          echo GOBIN=`go env GOPATH`/bin >> $GITHUB_ENV
          GOBIN=$(echo `go env GOPATH`/bin)

      - name: Dependencies
        run: make all-dependencies

      - name: Generate deepcopy
        run: make generate-deepcopy

  test:
    name: Test and linting
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Go 
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ^1.15

      - name: Setup env
        run: |
          sudo apt install build-essential
      
      - name: Linting
        run: |
          make fmt
          make vet

  generate:
    name: Generate yamls
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Go 
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ^1.15

      - name: Setup env
        run: |
         sudo apt install build-essential
         make all-dependencies

      - name: Generate deploy yamls
        run: |
          make create-dir
          make generate-crds
          make kustomize-crds
          make kustomize-controller IMG=${IMG}
