name: Create imagePullSecret for cluster in secret KUBE_CONFIG

on: [push]

jobs:
  create:
    name: Create secret
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, 'create secret')"
    steps:
      - uses: actions/checkout@v2.3.4

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker
      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GCE_ZONE }}

      - name: Install secret
        run: |-
          AUTH=`echo -n ${{ secrets.GITPKGS_USERNAME }}:${{ secrets.GITPKGS_PASSWORD }} | base64`
          echo '{"auths":{"docker.pkg.github.com":{"auth":$AUTH}}}' | kubectl create secret generic github-pkg --type=kubernetes.io/dockerconfigjson --from-file=.dockerconfigjson=/dev/stdin --namespace ppw-operator-system
          echo '{"auths":{"docker.pkg.github.com":{"auth":$AUTH}}}' | kubectl create secret generic github-pkg --type=kubernetes.io/dockerconfigjson --from-file=.dockerconfigjson=/dev/stdin