name: Create imagePullSecret for cluster in secret KUBE_CONFIG

on:
  push:
    branches: [dev]

jobs:
  create:
    name: Create secret
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Log into registry
        run: echo "${{ secrets.GITPKGS_PASSWORD }}" | docker login docker.pkg.github.com -u ${{ secrets.GITPKGS_USERNAME }} --password-stdin

      - name: Install secret from docker conf
        uses: actions-hub/kubectl@v1.14.3
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f https://k8s.io/examples/application/shell-demo.yaml
