name: Create imagePullSecret for cluster in secret KUBE_CONFIG

on: [push]

jobs:
  create:
    name: Create secret
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, 'create secret')"
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.GITPKGS_USERNAME }}
          password: ${{ secrets.GITPKGS_PASSWORD }}

      - run: cat $HOME/.docker/config.json

      - name: Install secret from docker conf
        uses: actions-hub/kubectl@v1.17.9-fix
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args:  create secret docker-registry regcred --docker-server=docker.pkg.github.com --docker-username=${{ secrets.GITPKGS_USERNAME }} --docker-password=${{ secrets.GITPKGS_PASSWORD }}
