name: Ppw-operator deploy into a cluster

on:
  push:
    branches: [dev]
  
jobs:
  deploy:
    name: Setup enviroment
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2.3.4

      # - name: Print kubecalster version
      #   uses: actions-hub/kubectl@v1.17.9
      #   env:
      #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      #   with:
      #     args: version
      #     #args: apply -f https://k8s.io/examples/application/shell-demo.yaml
