name: Ppw-operator deploy into a cluster

on:
  push:
    branches: [dev]
  
jobs:
  deploy:
    name: Setup enviroment
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        
      - name: Set up kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
