name: Ppw-operator deploy into a cluster

on:
  push:
    branches: [dev]
  
jobs:
  deploy:
    name: Setup enviroment
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f https://k8s.io/examples/application/shell-demo.yaml
