name: Ppw-operator generate additions

on:
  push:
    branches: [dev]

env:
  IMG: ppw-operator
  
jobs:
  setup:
    name: Setup enviroment
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        
      - name: Set up Go 
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ^1.15
          
      - name: Set up gcc
        run: sudo apt update && sudo apt install build-essential

      - name: Configure go
        run: |
          mkdir -p ~/go_projects/{bin,src,pkg}
          export GOPATH="$HOME/go_projects"
          export GOBIN="$GOPATH/bin"
          export PATH=$PATH:"$GOBIN"

      - name: Dependencies
        run: make all-dependencies

      - name: Linting
        run: |
          make fmt
          make vet

      - name: Generate deepcopy
        run: make generate-deepcopy

      - name: Generate deploy yamls
        run: |
          make generate-crds
          make kustomize-crds
          make kustomize-controller IMG=${IMG}
