name: Ppw-operator fully build

on:
  workflow_dispatch:
#  push:
#    branches: [dev]
  
jobs:
  setup:
    name: Setup enviroment
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        
      - name: Set up Go 
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ^1.15
          
      - name: Setting up
        run: make setup

          
